substancesList = [
    "MDMA",
    "MDE",
    "MDA",
    "5-APB",
    "Methlyone",
    "Ethylone",
    "Butylone",
    "Mephedrone",
    "MDPV",
    "Alpha-PVP",
    "Methamphetamine",
    "Amphetamine",
    "BZP",
    "TFMPP",
    "PMA",
    "PMMA",
    "2C-B",
    "2C-I",
    "Ketamine",
    "Methoxetamine",
    "DXM",
    "Codeine",
    "Morphine",
    "Oxycodone",
    "Heroin",
    "Mescaline",
    "Cocaine",
    "Aspirin",
    "Sugar",
    "LSD",
    "5-MEO-MIPT",
    "5-MEO-DMT",
    "DMT",
    "Psilocin",
    "Psilocybin",
    "25i-NBOME",
    "5-MEO-AMT",
    "5-MEO-DIPT",
    "4-ACO-DMT",
    "AMT"
]
reagentsList = [
    ["Marquis",
     "Paul Waldorf",
     "Standard single bottle reagent"
    ],
    ["Mecke",
     "Paul Waldorf",
     "Standard single bottle reagent"
     ],
    ["Mandolin",
     "Paul Waldorf",
     "Standard single bottle reagent"
     ],
    ["Simon",
     "Paul Waldorf",
     "Two part reagent typically used for MDE/MDA/MDMA differentiation"
     ],
    ["Froehde",
     "Paul Waldorf",
     "Advanced single bottle reagent"
     ],
    ["Liebermann",
     "Paul Waldorf",
     "Advanced single bottle reagent"
     ],
    ["Folin",
     "Paul Waldorf",
     "Two part specialty bottle reagent"
     ],
    ["Ehrlich",
     "Paul Waldorf",
     "Specialty reagent for detecting presence of indole structures"
     ]
]

materialList = {
    "Geltab",
    "Blotter",
    "Pressie",
    "Powder",
    "Crystal",
    "Microdot",
    "Liquid - Small Volume",
    "Liquid - Large Volume",
    "Liquid - Beverage",
    "Pill - RX",
    "Fungus",
    "Plantmatter",
    "Dosed Food",
    "E-Liquid",
    "Herb - Laced"
    "Capsule",
    "Syringe",
    "Dipped Media",
    "Patch",
    "Tar",
}

