@startuml

skinparam defaultFontName Courier

Class Chapters {
    UUID     ★ id                     
    UUID     ☆ author                 
    UUID     ☆ presidentPrimaryContact
    UUID     ☆ secretary              
    UUID     ☆ treasurer              
    UUID     ☆ vicePresident          
    VARCHAR  ⚪ email                  
    VARCHAR  ⚪ facebook               
    VARCHAR  ⚪ name                   
    VARCHAR  ⚪ primaryphone           
    VARCHAR  ⚪ snapchat               
    DATETIME ⚪ ts                     
    VARCHAR  ⚪ twitter                
    VARCHAR  ⚪ website                
}

Class Colors {
    UUID    ★ id  
    INTEGER ⚪ hex 
    VARCHAR ⚪ name
}

Class Events {
    UUID     ★ id    
    UUID     ☆ author
    VARCHAR  ⚪ city  
    VARCHAR  ⚪ name  
    VARCHAR  ⚪ region
    VARCHAR  ⚪ state 
    DATETIME ⚪ ts    
    INTEGER  ⚪ year  
}

Class ExpectedReactions {
    UUID ★ colorid    
    UUID ★ reactionid 
    UUID ★ substanceid
}

Class MaterialType {
    UUID    ★ id         
    TEXT    ⚪ description
    VARCHAR ⚪ name       
}

Class ReagentColorList {
    UUID ★ color   
    UUID ★ reaction
}

Class Reactions {
    UUID    ★ id         
    UUID    ☆ reagentid  
    INTEGER ⚪ reactionint
}

Class Reagents {
    UUID     ★ id         
    UUID     ☆ author     
    TEXT     ⚪ description
    VARCHAR  ⚪ name       
    DATETIME ⚪ ts         
}

Class Sample {
    UUID     ★ id              
    UUID     ☆ eventid         
    UUID     ☆ finalconclusion 
    UUID     ☆ initialsuspect  
    UUID     ☆ recorder        
    UUID     ☆ shiftlead       
    UUID     ☆ tester          
    UUID     ☆ typeid          
    BOOLEAN  ⚪ conclusiveresult
    TEXT     ⚪ description     
    BOOLEAN  ⚪ groundscore     
    DATETIME ⚪ ts              
}

Class Substances {
    UUID    ★ id  
    VARCHAR ⚪ name
}

Class Survey {
    INTEGER ★ id        
    INTEGER ☆ questionid
    TEXT    ⚪ answer    
}

Class TestResults {
    UUID ★ id           
    UUID ☆ reactioncolor
    UUID ☆ reactionid   
    UUID ☆ sampleid     
}

Class Questions {
    INTEGER  ★ id    
    UUID     ☆ author
    TEXT     ⚪ detail
    DATETIME ⚪ ts    
}

Class Users {
    UUID     ★ id         
    UUID     ☆ chapter    
    VARCHAR  ⚪ _password  
    VARCHAR  ⚪ email      
    VARCHAR  ⚪ facebookurl
    VARCHAR  ⚪ fullname   
    VARCHAR  ⚪ instagram  
    DATETIME ⚪ ts         
    VARCHAR  ⚪ username   
}

Chapters <--o Users: presidentPrimaryContact

Chapters <--o Users: vicePresident

Chapters <--o Users: treasurer

Chapters <--o Users: secretary

Chapters <--o Users: author

Events <--o Users: author

ExpectedReactions <--o Substances: substanceid

ExpectedReactions <--o Reactions: reactionid

ExpectedReactions <--o Colors: colorid

ReagentColorList <--o Reactions: reaction

ReagentColorList <--o Colors: color

Reactions <--o Reagents: reagentid

Reagents <--o Users: author

Sample <--o Events: eventid

Sample <--o Users: shiftlead

Sample <--o Users: tester

Sample <--o Users: recorder

Sample <--o MaterialType: typeid

Sample <--o Substances: initialsuspect

Sample <--o Substances: finalconclusion

Survey <--o Questions: questionid

TestResults <--o Sample: sampleid

TestResults <--o Reactions: reactionid

TestResults <--o Colors: reactioncolor

Questions <--o Users: author

Users <--o Chapters: chapter

right footer generated by sadisplay v0.4.8

@enduml