@startuml

skinparam defaultFontName Courier

Class Colors {
    UUID    ★ id
    INTEGER ⚪ hex
    VARCHAR ⚪ name
}

Class Events {
    UUID        ★ id
    UUID        ☆ author
    VARCHAR[50] ⚪ city
    VARCHAR[50] ⚪ name
    VARCHAR[25] ⚪ region
    VARCHAR[2]  ⚪ state
    DATETIME    ⚪ ts
    INTEGER     ⚪ year
}

Class ExpectedReactions {
    UUID ★ colorid
    UUID ★ reactionid
    UUID ★ substanceid
}

Class MaterialType {
    UUID    ★ id
    TEXT    ⚪ description
    VARCHAR ⚪ name
}

Class ReagentColorList {
    UUID ★ color
    UUID ★ reaction
}

Class Reactions {
    UUID    ★ id
    UUID    ☆ reagentid
    INTEGER ⚪ reactionint
}

Class Reagents {
    UUID     ★ id
    UUID     ☆ author
    TEXT     ⚪ description
    VARCHAR  ⚪ name
    DATETIME ⚪ ts
}

Class Sample {
    UUID     ★ id
    UUID     ☆ eventid
    UUID     ☆ finalconclusion
    UUID     ☆ initialsuspect
    UUID     ☆ recorder
    UUID     ☆ shiftlead
    UUID     ☆ tester
    UUID     ☆ typeid
    BOOLEAN  ⚪ conclusiveresult
    TEXT     ⚪ description
    BOOLEAN  ⚪ groundscore
    DATETIME ⚪ ts
}

Class Substances {
    UUID    ★ id
    VARCHAR ⚪ name
}

Class Survey {
    INTEGER ★ id
    INTEGER ☆ questionid
    TEXT    ⚪ answer
}

Class TestResults {
    UUID    ★ id
    UUID    ☆ reactionid
    UUID    ☆ sampleid
    VARCHAR ⚪ reactioncolor
}

Class Questions {
    INTEGER  ★ id
    UUID     ☆ author
    TEXT     ⚪ detail
    DATETIME ⚪ ts
}

Class Users {
    UUID         ★ id
    VARCHAR[128] ⚪ _password
    VARCHAR[50]  ⚪ chapter
    VARCHAR[50]  ⚪ email
    VARCHAR[50]  ⚪ facebookurl
    VARCHAR[100] ⚪ fullname
    VARCHAR[50]  ⚪ instagram
    DATETIME     ⚪ ts
    VARCHAR[42]  ⚪ username
}

Events <--o Users: author

ExpectedReactions <--o Substances: substanceid

ExpectedReactions <--o Reactions: reactionid

ExpectedReactions <--o Colors: colorid

ReagentColorList <--o Reactions: reaction

ReagentColorList <--o Colors: color

Reactions <--o Reagents: reagentid

Reagents <--o Users: author

Sample <--o Events: eventid

Sample <--o Users: shiftlead

Sample <--o Users: tester

Sample <--o Users: recorder

Sample <--o MaterialType: typeid

Sample <--o Substances: initialsuspect

Sample <--o Substances: finalconclusion

Survey <--o Questions: questionid

TestResults <--o Sample: sampleid

TestResults <--o Reactions: reactionid

Questions <--o Users: author

right footer generated by sadisplay v0.4.8

@enduml